
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: Chat.proto
namespace RoyNet.Server.GameEngine.Entity
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Chat_Send")]
    public partial class Chat_Send : global::ProtoBuf.IExtensible
    {
      public Chat_Send() {}
      
    private string _Text;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    public enum CMD_Chat
    {
      Send = 268435456
    }
  
}
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: Game.proto
namespace RoyNet.Server.GameEngine.Entity
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Game_Entered")]
    public partial class Game_Entered : global::ProtoBuf.IExtensible
    {
      public Game_Entered() {}
      

    private int _nothing = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nothing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(default(int))]
    public int nothing
    {
      get { return _nothing; }
      set { _nothing = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    public enum CMD_Game
    {
      Entered = 0
    }
  
}